package ru.bioinf.rosalind.stringAlgorithms;

/**
 * Проблема №3
 * @see <a href = http://rosalind.info/problems/revc/> Complementing a Strand of DNA.</a>
 * 
 * @author vveprinsky
 */
public class Revc {

	public static void main(String[] args) {
		String stringDNA = "TAGATAAAGCGGGTCAAATCTTGAGTTGCAGGTCCGATACTCGACCAGAGCGTAGGCTTGATTTACAGTGCAAATCGTTGGTTATTCGATTCTTTACAGAAAAGTGCGCTCACGACAAGTGTGGACGTTTAATCCAGGATAACTGTCGAAGGAAGCATCCGCAGCTTACCCAATAGGTTCCACCGGGGGATGCGCTATAAAGGTATGCTTCCCTCCAGGAAGGATTACTCGGGGGAAAGCCGGTGATCATAAGCCCTTTTTTCTGTGAGATTGTTGGATATGCCTGCAAGTGCGCGTCATACATTACGCATTAGCTGGGTGCCATTCCCCTTCACGACCCTTACATGACATTGTGGCATGTTTGGTGGGTGTCCCTTTACGCTTATGAAGTCCAGTTCCACCGGGAGCGGCTAATATACCTGGAAAGTCAATGTCACGCGTCACGCCGTACGTAACAATGTTACTTTGTCACCCAGCATACGCGTGCACCGCTATAAGATCGTCATACAAGCCACGCAAACCAAGTGAATACGGCAGATAGAGCGCGCAGCTCTGTATGGGTTACGCAAGGTTACCCCCGTGCCCGCGCTCACCGAGCTACGACAAGCAGATAACCAGAGAAATCGCGTATGGGACCTGCATTCCGATATGATCACCAAGCCACGACATGCGGTCCGCAAGGAATTGTATCGAGCAGCAGGCAGGTATACTCGTTTATCCCGGGCCCGGATGCCGTCATCACGTTACAGTCTAATAGCCTCTCGCCGGGCACACTAGGAATAAAACGCACCATGCCTCAGCCGATTGCGTCAGGCTATAAAAGCACATCAATCAGACTGATAAACGCCGCTGAGTCATTTCCCGCACTGACTCCAGCCAAGCATCATGGACTGTGCGCAGGATCTAGCTATGGCGCTACCCCGGGGTGGGTCGATTAAACAGT";
		System.out.println(reverseComlement(stringDNA));
	}

	public static String reverseComlement(String str){
		char[] dna = str.toCharArray();
		char[] dnaReverseComplement = new char[dna.length];
		int j = 0;
		for (int i = dna.length-1; i >=0 ; i--) {
			switch (dna[i]) {
			case 'A' : dnaReverseComplement[j] = 'T';break;
			case 'T' : dnaReverseComplement[j] = 'A';break;
			case 'C' : dnaReverseComplement[j] = 'G';break;
			case 'G' : dnaReverseComplement[j] = 'C';break;
			}	
			j++;
		}
		return new String(dnaReverseComplement);
	}
}
