package ru.bioinf.rosalind.stringAlgorithms;

/**
 * Проблема №2
 * @see <a href = http://rosalind.info/problems/rna/> Transcribing DNA into RNA.</a>
 * 
 * @author vveprinsky
 */
public class RNA {

	public static void main(String[] args) {
		String stringDNA = "TTGTTTTTCTTCCGGTCTTTCTCGACTGCGATTATCTAGCTATCAGCACGAGCACTTGATATGGTAAACGGTACGGTGTAACGGCTTCTTATGTCCCGGCTCCCCTCACTCTACTCACGAACCCGAACCAACAGAGTGTTGCCATGTACAGAGTGATCTTGGAGTCACACCACCGAGTCTCTAAGCCGGGGGCCTGCCCCGGTCACGTATGAGTATCATACGTTGGCTGACAGCCGGTTTTAGCGGCGAACGAGATGAGGTCAGCTCAACGAGAGAGTACAATATATTTCTACGCCTGCTCGAAAGTACTCGTACCTGCATGCTGGCCTTCGAACTCGTGAGTCTACTTATGATCGACCAGTGGTCCTTCTGGTACGTTTGCCGGGAGCGTTCCGAACCACTTCCTGTACGTTTTGTAGGTGCGTACGCGGGCGCTCGGTGGCAGAGACGCCTGTAATAATTCTCAGTATAGAGCGGTTGGGTCAGGGAACCGGGCCTTCCATTATAGTAACCTCCGTAGCAGGCTAAGTCACAAGTCGCTAGGCTCACCGTTGGCGAGCTGGTTCAAAAATAATGTCTCGCGGCCCTCCACCGTGCCTGTTCATATTGGTTCGCTGAGCTGGAGGTTTACGAGTGACGGGAAAAGTCATTGATCACCTGTTAGAGCTAGCTGTTAGGGTGTTCTTGTTGTTTAAGAGGGAAGGTTTAGAGGAAAATCTGGTGACAAACTGACGTTGTGAGATACAGCGAATGCAATAGATTCCGCGGGGCCAGCCACGGCTTAATAAGGGCCGGGACGACCATTCCTTAGAATCTTTCTGGCTTGCACCTGACGGCGCTGCCAACTTTTAGAATACGGCGCTACCAAGTCCAGTACGATTATGGCAAGAGGAGCTTCCTACTTCGCGCGGCGACGTTAAGATAAGA";
		String stringRNA = stringDNA.replaceAll("T", "U");
		System.out.println(stringRNA);
	}

}
