package ru.bioinf.rosalind.alignment;

/**
 * Проблема №6
 * @see <a href = http://rosalind.info/problems/hamm/> Counting Point Mutations. </a>
 * 
 * @author vveprinsky
 */
public class Hamm {

	
	public static void main(String[] args) {
		String s = "CGCAGGTTAACACAATCTTGAAGTGTGTATCACGGTAGTGGCACCCATGAGATTGGGCACGACGGAGTAAAACGTACTCAAATGCCCCGGTGGTACAAGATGAGACCCCCCTTGATTGGCTTCAGGCCGTCGTTTTATTGTAGCCAGATATTTTGTATCCCCACTAAACGAGCTGGCCTCCAACAAAACCTCCCACATCGACGAATGCCTATCGTTGAAACTCCAGCGAGTCGTAACACCGAGGTAAATGTTGGGTCGGTGGGACCGGACAAAGCGTTAATACTATATACTCTAACATTTGGGTGTGTGGCTTTCAATCGTCCATTTAATTTGATTCAGTTGACGCGCGGTATTAGCAAAAGTCGCTCCCGTCTAAATAACCCCCATTCTTCCACAGCGATCGGGACATACTTAACATTCGACAGCATGTGTTAGTACTGCCAGGTAGAAACTAAATTTTTGAGAAGTTACCGATATATCTCATTCTAGATCCTTCAGTTCTCTGGCCTACCATCTTTTTTGTATAGCTCTGCATGTACGGCTTTTCTCTATAGTGCGTTTTGGGGCGGACCACAGAATTTCCAAAGTGGTTTACGGATCCCCGCGATTCCTTTACCATAATAAGGCGGGCAGGAATCAGCTGTGGAAACGACCACAAAGGTTATAGTTCACCGCACCTCCTGGTCTTGGCCTACACGAAATAAAAATTCGTAGTCACTGGTTCTTAGAAGATTGGTTGGCCGACACATAAGATTCTATCCCCAGTGGGATAGTCCCCGTCACCAAAGTATCATTGATTGTCATGAATGGTAACGGCTGTGATCGGTTTTGTTCTACACAACGAGTCTGAATCGAGTGGAGAGGTTACCTCAGTCTCGAAGGTACAAAATTCCCCGTTCAAGTGTATTGGAGGATGGCCAGGGGTTCACGTAG";
		String t = "AGGAAAATGACAGAATCTAGGAGAGTGCTCCCGCGACCTTGTACTTCAGGCAATCGCAAATGGAGCCTTCATCGTAATCCACCGTCCCGCGAGTACGCCACCAAATTTCCCGAGATTACATTGGCGCTTTTATTAGACTGGGACCGCAGAAATACAGTTTTGAGCAACACTCCTATCCTCCACCAAAATCGCGCATACGACCGAAGACCTAAAGTTGAACGACCAGCGAATCATATGTCTGAAGGAGATTTGTGGTCACTGGAACCGAACAACACCTTGCTATCTTTTTACCAAAATAGTATGCTGGAAAATCTACCTGTTCCTTATGATTTGATCGTGATGCTTCACGTTAATTGGAAGATTTGTAACCGTCTATTGCCGCCCCAATATTACAACCCGGCTTGGACCTGAATTACACTCTCCAGCGTTGGTTAGTGGAGACTGGCGATTGTACGCTTTCTGTGAGGTAACTGATGCTGTCCCTTATAAATCCTACGTTTGTCTTGGTTAGACTCTTCCGTGGGTATCACTAAATGCCCGGGTTAGGTACATTGTGACTTTAAAGGCGGCGTACTTATTTGCCACATTCCACCAATGTAAGCCGTCATGCCCGGGGCATTATAATAATGTGGCGCTTCCCCTGGGCAAGAGAATCGTCAACTGACGATTGTCATCACGTGTAACTGTTGGCCCGGAACATATAGTGATCCCTAGATAGTGCATGGAAAAAGCTCAATGATTTTACAAACATTGGTCTATCGTGACTCGGATGGCATGGAACATCGAAAGTCACCCGATATGCATTACATGTGGCTTGAGTTATAACAATCGTTCAACACATCGAGTCTTCCGGGTCTGCAGAGGTTACCGGATACTCGATAGAATCAATTTGCCCGTCCCTGTATATCGCCAGTCATTTAGCTCGCAGCCGGG";

		System.out.println(calcHammingDistance(s, t));
	}

	/**
	 * Вычисляет расстояние Хеминга для двух последовательностей (одинаковой длины).
	 */
	public static long calcHammingDistance(String s, String t) {
		char[] sDNA = s.toCharArray();
		char[] tDNA = t.toCharArray();
		return calcHammingDistance(sDNA, tDNA);
	}

	/**
	 * Вычисляет расстояние Хеминга для двух последовательностей (одинаковой длины).
	 */
	public static long calcHammingDistance(char[] s, char[] t) {
		long distanceHamming = 0;
		for (int i = 0; i < s.length; i++) {
			if (s[i]!=t[i]) {
				distanceHamming++;
			}
		}
		return distanceHamming;
	}
	
}
